
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QFrame{\n"
"    border : none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setVerticalSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_url = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_url.setEnabled(False)
        self.textEdit_url.setObjectName("textEdit_url")
        self.gridLayout.addWidget(self.textEdit_url, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_output_folder = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_output_folder.setReadOnly(True)
        self.lineEdit_output_folder.setObjectName("lineEdit_output_folder")
        self.gridLayout.addWidget(self.lineEdit_output_folder, 2, 1, 1, 1)
        self.output_folder_btn = QtWidgets.QPushButton(self.frame_4)
        self.output_folder_btn.setObjectName("output_folder_btn")
        self.gridLayout.addWidget(self.output_folder_btn, 2, 2, 1, 1)
        self.lineEdit_input_file = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_input_file.setReadOnly(True)
        self.lineEdit_input_file.setObjectName("lineEdit_input_file")
        self.gridLayout.addWidget(self.lineEdit_input_file, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.input_file_btn = QtWidgets.QPushButton(self.frame_4)
        self.input_file_btn.setObjectName("input_file_btn")
        self.gridLayout.addWidget(self.input_file_btn, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.submit_btn = QtWidgets.QPushButton(self.frame_4)
        self.submit_btn.setObjectName("submit_btn")
        self.gridLayout.addWidget(self.submit_btn, 3, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.frame_5)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.label_message = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(25)
        self.label_message.setFont(font)
        self.label_message.setText("")
        self.label_message.setObjectName("label_message")
        self.verticalLayout_3.addWidget(self.label_message, 0, QtCore.Qt.AlignHCenter)
        self.open_folder_btn = QtWidgets.QPushButton(self.frame_5)
        self.open_folder_btn.setObjectName("open_folder_btn")
        self.verticalLayout_3.addWidget(self.open_folder_btn, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("padding:5px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setStyleSheet("padding:5px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignBottom)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "html2pdf"))
        self.label.setText(_translate("MainWindow", "Html To Pdf Converter"))
        self.textEdit_url.setPlaceholderText(_translate("MainWindow", "Enter Urls separated by newline"))
        self.label_4.setText(_translate("MainWindow", "Input files"))
        self.lineEdit_output_folder.setPlaceholderText(_translate("MainWindow", "Select Output Folder"))
        self.output_folder_btn.setText(_translate("MainWindow", "..."))
        self.lineEdit_input_file.setPlaceholderText(_translate("MainWindow", "Select Files"))
        self.checkBox.setText(_translate("MainWindow", "From Urls"))
        self.input_file_btn.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "Output folder"))
        self.submit_btn.setText(_translate("MainWindow", "Convert"))
        self.open_folder_btn.setText(_translate("MainWindow", "Open Folder"))
        self.label_2.setText(_translate("MainWindow", "By : Ay0ub N0uri"))
        self.label_3.setText(_translate("MainWindow", "V0.5"))
